name: week11 Task

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo4.4.1
        ports: -27017:27017

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - run: yarn
      - run: yarn build
      - run: yarn test
    env:
      MONGO_URI: mongodb://localhost/test
# version: 2
# jobs:
#   build:
#     docker:
#       - image: cimg/<language>:<version TAG>
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: <command>
#   test:
#     docker:
#       - image: cimg/<language>:<version TAG>
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#     steps:
#       - checkout
#       - run: <command>
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test
